### ISSUE TITLE
What's torch_sparse version?

### ISSUE THREAD

**Issue by blacktanktop** [drorlab/gvp-pytorch#3]
I didn't see it in the requirements, but torch_sparse seems to require it, so I installed 0.6.12, but I get the following error: torch_sparse seems to have the same problem, but I want to know what version configuration is in this repository. Please let me know the results of `pip list` or `conda list` or something like that .

```
Traceback (most recent call last):
  File "/home/gvp-pytorch/run_cpd.py", line 32, in <module>
    import gvp.data, gvp.models
  File "/home/gvp-pytorch/gvp/__init__.py", line 4, in <module>
    from torch_geometric.nn import MessagePassing
  File "/home/.pyenv/versions/gvp-pytorch/lib/python3.6/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/.pyenv/versions/gvp-pytorch/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/.pyenv/versions/gvp-pytorch/lib/python3.6/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/.pyenv/versions/gvp-pytorch/lib/python3.6/site-packages/torch_sparse/__init__.py", line 16, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'
```

**Comment by blacktanktop** [comment]
After much consideration, I solved the problem by installing the modules around torch-geometric as follows (It was simply a CUDA problem).

````
# required gcc >= 5.0
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.8.1+cu102.html
```
